// Service project stories. Every fact here comes from the Balita or the RY 2025–26 report of
// IPP Raoul C. Creencia (107th anniversary souvenir program); sources are listed on each page.
// Photos: '/assets/projects/...' are clean originals pulled from the Balita PDFs (no captions or crops baked in).
// Photos of patients, infants and minors are deliberately left out until written consent is on file.
module.exports = [
  {
    slug: 'typhoon-relief-2025',
    archive: 'typhoon relief',
    card: 'Typhoon and flood relief',
    title: 'Relief for families hit by typhoons and floods',
    kicker: 'Disaster response · OPLAN CARE',
    dek: 'From Typhoon Crising in 2025 to the floods of September 2026, members have waded in with sleeping mats, food, medicines and livelihood help for families in Tondo, Cavite, Bulacan and Pampanga, working alongside neighboring Rotary clubs.',
    hero: { src: '/assets/projects/relief-van-handoff-2026.jpg', w: 1800, h: 1200, alt: 'President Reginald Yu, in a life vest, passes relief bags from a van to volunteers who load them onto boats for flood-hit barangays in Calumpit, Bulacan, September 2026' },
    facts: [
      ['When', 'July 2025 – September 2026'],
      ['Where', 'Tondo, Manila · Rosario, Cavite · Calumpit, Obando and Paombong, Bulacan · Macabebe and Masantol, Pampanga'],
      ['Led by', 'President Raoul C. Creencia (RY 2025–26) and President Reginald T. Yu (RY 2026–27)'],
      ['Cause', 'Disaster response'],
    ],
    need: [
      'Floods keep returning to the same low-lying communities. In 2025, Typhoon Crising displaced families in Tondo and hurt the livelihoods of fishing families in Rosario, Cavite. In September 2026, floodwater up to five feet deep cut off Barangays Gugo, Santa Lucia and Bulusan in Calumpit, Bulacan, where ordinary relief vehicles could not reach.',
    ],
    did: [
      ['23 July 2025', 'Brgy. 128, Balut, Tondo', '400 plastic sleeping mats for evacuees at the Tondo Evacuation Center.'],
      ['July 2025', 'Brgy. 105, Tondo', 'Bed mats for families displaced by the storm.'],
      ['24 July 2025', 'Brgy. Ligtong, Rosario, Cavite', '“Sagip Mangingisda”: support for 100 fishing families, with RC Cavite Export Processing Zone, RC Cavite Uptown, RC Dasmariñas, RC Rosario and other clubs.'],
      ['27 July 2025', 'Brgy. Calizon, Calumpit, Bulacan', 'Relief goods for 100 families, with RC Calumpit.'],
      ['2 August 2025', 'Brgy. Catanghalan, Obando, Bulacan', 'Essential medicines for affected families, with RC Obando Centro.'],
      ['3 August 2025', 'Brgy. Pinalagdan, Paombong, Bulacan', 'Relief packs for 100 families, with the Rotaract Club of Manila and ALC Media–DWIZ.'],
      ['17 August 2025', 'Colegio de Calumpit, Bulacan', 'A second relief operation in Calumpit with RC Calumpit.'],
      ['September 2026', 'Calumpit, Bulacan and Macabebe and Masantol, Pampanga', '“Kalinga sa Kalumpit”: with RC Calumpit, members led by President Reginald T. Yu went by boat and on foot through floodwater up to five feet deep to deliver 210 relief packs in Barangays Gugo, Santa Lucia and Bulusan, then rice packs for 70 more families in Pampanga.'],
    ],
    result: [
      ['1,200', 'families supported by the Club’s typhoon and earthquake relief (OPLAN CARE) during RY 2025–26, in nine locations'],
      ['400', 'sleeping mats for evacuees in Tondo'],
      ['280', 'families reached in the September 2026 flood relief in Bulacan and Pampanga'],
    ],
    partners: ['Rotary Club of Calumpit', 'Rotary Club of Obando Centro', 'Rotary Clubs of Cavite Export Processing Zone, Cavite Uptown, Dasmariñas, Rosario, Cavite Premier, Imus Independencia, Malate Prime and Tagaytay City', 'Rotaract Club of Manila', 'ALC Media–DWIZ'],
    next: 'The Club responds again whenever a disaster strikes. Gifts to the Club’s projects and members’ time make the next response possible.',
    gallery: [
      { src: '/assets/projects/relief-bancas-2026.jpg', caption: 'Volunteers load relief bags onto boats, the only way to reach Barangays Gugo, Santa Lucia and Bulusan while floodwater cut them off, September 2026.' },
      { src: '/assets/projects/relief-lifevests-2026.jpg', caption: 'Members of the Rotary Clubs of Manila and Calumpit put on life vests before heading out by boat to the flooded barangays.' },
      { src: '/assets/projects/relief-bulusan-2026.jpg', caption: 'President Reginald Yu hands relief goods to a resident of Barangay Bulusan, where floodwater still surrounded homes.' },
      { src: '/assets/projects/relief-unloading-2026.jpg', caption: 'Members unload relief goods straight into the flooded community and carry each bag by hand.' },
      { src: '/assets/projects/relief-raft-2026.jpg', caption: 'A resident of Barangay Bulusan tows his relief goods home on a raft of used plastic containers.' },
      { src: '/assets/projects/relief-rosario-2.jpg', caption: '“Sagip Mangingisda”: rice and relief goods for fishing families in Barangay Ligtong, Rosario, Cavite, 24 July 2025.' },
    ],
    sources: [
      ['/balita/4059/typhoon-response-and-relief-efforts', 'Balita No. 4059: Typhoon response and relief efforts'],
      ['/balita/4061/rc-manila-continues-its-relief-operations-in-calumpit-bulacan', 'Balita No. 4061: RC Manila continues its relief operations in Calumpit'],
      ['/balita/4061/disaster-relief-operation-in-calumpit-featured-on-dwiz-news', 'Balita No. 4061: The Calumpit operation on DWIZ News'],
      ['/balita/4106/kalinga-sa-kalumpit', 'Balita No. 4106: Kalinga sa Kalumpit'],
      [null, 'RY 2025–26 report of IPP Raoul C. Creencia'],
    ],
  },
  {
    slug: 'pgh-neonatal-care',
    archive: 'Philippine General Hospital',
    card: 'Newborn care at PGH',
    title: 'Life-saving equipment for newborns at PGH',
    kicker: 'Maternal and child health · Rotary Global Grant',
    dek: 'With the Rotary Club of Kangjin-Tamjin in Korea, the Club equipped the Neonatal Intensive Care Unit of the Philippine General Hospital, the country’s largest public hospital, through a Rotary Foundation Global Grant.',
    hero: { src: '/assets/projects/pgh-program.jpg', w: 964, h: 557, alt: 'IPP Raoul Creencia presents the background of Global Grant #2682583 to Rotarians from Manila and Kangjin-Tamjin at UP–PGH, with the donated neonatal care units lined up at the side, 4 September 2026' },
    facts: [
      ['Grant', 'Rotary Foundation Global Grant #2682583, “Strengthening Neonatal Care through Life-Saving Equipment Support”'],
      ['Where', 'Neonatal Intensive Care Unit, UP–Philippine General Hospital, Manila'],
      ['Budget', 'US$50,000 in total, shared between the partner districts and clubs'],
      ['Area of focus', 'Maternal and child health'],
    ],
    need: [
      'On 13 July 2025, President Raoul Creencia and the visiting delegation from Korea inspected PGH’s neonatal intensive care unit and pediatric wards with Dr. Jenny Yap of the NICU. They saw a real need for more equipment, such as incubators, radiant warmers and breastmilk analyzers.',
    ],
    did: [
      ['12 July 2025', 'Hyatt Hotel, City of Dreams', 'The Club signed a Memorandum of Understanding with the Rotary Club of Kangjin-Tamjin (RI District 3610, Korea), led by President Bang Jae Nam, for a global grant with PGH.'],
      ['13 July 2025', 'PGH Neonatal Intensive Care Unit', 'Both clubs toured the NICU and pediatric wards to confirm what equipment was needed.'],
      ['RY 2025–26', 'Club fundraising', 'The Club began raising its share of the grant. Members’ Paul Harris contributions to The Rotary Foundation could be directed to the project.'],
      ['June 2026', '36th Weekly Membership Meeting', 'The Club and UP–PGH signed the Memorandum of Agreement for Global Grant #2682583. Dr. Esterlita Uy, Chief of the Division of Newborn Medicine, signed for PGH and President Raoul Creencia for the Club, with President-elect Reggie Yu and Secretary Anton Mauricio as witnesses.'],
      ['4 September 2026', 'UP–PGH Neonatal Intensive Care Unit', 'The neonatal intensive care equipment was formally turned over to PGH, with an 18-member delegation from the Rotary Club of Kangjin-Tamjin. A Global Grant and Four-Way Test marker was unveiled at the NICU ward.'],
    ],
    result: [
      ['Delivered', 'neonatal intensive care equipment turned over to the PGH NICU'],
      ['US$50,000', 'total budget for NICU equipment, shared between the partner districts and clubs'],
      ['2', 'countries: Rotary clubs in the Philippines and Korea working together'],
    ],
    partners: ['Rotary Club of Kangjin-Tamjin (RI District 3610, Korea)', 'UP–Philippine General Hospital, Division of Newborn Medicine', 'Rotary Districts 3610 and 3810', 'The Rotary Foundation'],
    next: 'The equipment is now in use at the NICU. The Rotary Club of Kangjin-Tamjin hopes to make the partnership an annual effort.',
    gallery: [
      { src: '/assets/projects/pgh-presenting-units.jpg', caption: 'A speaker points out the donated neonatal care units during the turnover ceremony at UP–PGH, 4 September 2026.' },
      { src: '/assets/projects/pgh-unveiling.jpg', caption: 'Unveiling the Global Grant #2682583 and Four-Way Test marker at the NICU ward.' },
      { src: '/assets/projects/pgh-translating.jpg', caption: 'Rotarian Ingil Ra translates for IPP Raoul Creencia so the Korean delegation can follow the program.' },
      { src: '/assets/projects/pgh-nicu-tour-2025.jpg', caption: 'Rotarians and NICU staff tour the PGH Neonatal ICU on 13 July 2025 to confirm what equipment was needed.' },
    ],
    sources: [
      ['/balita/4057/visit-to-the-philippine-general-hospital', 'Balita No. 4057: Visit to the Philippine General Hospital'],
      ['/balita/4057/signing-of-mou-with-rc-gangjintamjin-for-a-global-grant-project', 'Balita No. 4057: Signing of the MOU with RC Kangjin-Tamjin'],
      ['/balita/4057/presidents-message', 'Balita No. 4057: President’s Message'],
      ['/balita/4095/36th-weekly-membership-meeting-club-awards-2026-valedictory-address', 'Balita No. 4095: 36th Weekly Membership Meeting recap'],
      ['/balita/4105/formal-turnover-of-neonatal-care-equipment-to-the-philippine-general-hospital', 'Balita No. 4105: Formal turnover of neonatal care equipment to PGH'],
    ],
  },
  {
    slug: 'bayanan-elementary-school',
    archive: 'elementary school',
    card: 'Bayanan Elementary School',
    title: 'A safer school for the children of Bayanan',
    kicker: 'Basic education and literacy',
    dek: 'Some pupils of Bayanan Elementary School in Baco, Oriental Mindoro, walk up to three hours and cross a river on a bamboo bridge to reach two leaking classrooms. The Club has committed to rehabilitate the school.',
    hero: { src: '/assets/projects/bayanan-river.jpg', w: 1076, h: 717, alt: 'President Reginald Yu walking along the rocky slopes of the Bayanan River, the route many pupils take to school' },
    facts: [
      ['Where', 'Bayanan Elementary School, Baco, Oriental Mindoro, within the ancestral domain of the Mangyan people'],
      ['Pupils', 'About 197, Nursery to Grade 6, around 75 percent of them Mangyan children'],
      ['Led by', 'President Reginald T. Yu (RY 2026–27)'],
      ['Area of focus', 'Basic education and literacy'],
    ],
    need: [
      'Some children trek for as long as three hours each day through rocky terrain, often without adequate footwear, and cross the Bayanan River on a makeshift bamboo bridge. At the end of that journey is a two-classroom building with no ceiling, makeshift windows and doors, a roof that leaks when it rains, no proper partition between the classrooms, and comfort rooms that need significant improvement.',
    ],
    did: [
      ['1 September 2026', 'Bayanan Elementary School', 'President Reginald T. Yu, Director Nico Valencia, Director Teddy Kalaw, Club Secretary Albert Alday, Club Auditor Gani Macatoman and Global Grant Chair Aries Balanay inspected the school and interviewed School Head Mrs. Ednalin Dunday and Barangay Chairman Nitoy A. Remnayon.'],
      ['September 2026', 'Land for the school', 'Director Nico Valencia began securing a Deed of Donation from the Valencia family, which owns the land the school stands on. Once completed it goes to the Department of Education, clearing the way for the agency to rebuild and rehabilitate the school.'],
    ],
    result: [
      ['197', 'pupils who stand to benefit'],
      ['5', 'repairs committed: ceilings, roof, doors and windows, classroom partition and comfort rooms'],
    ],
    resultText: 'The Club has also committed to install a Rotary Four-Way Test marker at the school and to donate diapers and milk to families with infants and young children.',
    quote: 'No community, no matter how remote, should ever be beyond the reach of compassion and service.',
    partners: ['Bayanan Elementary School', 'Barangay Bayanan', 'The Valencia family, landowners', 'Department of Education'],
    next: 'The Deed of Donation is completed and submitted to the Department of Education, resources are mobilized, and the rehabilitation is carried out.',
    gallery: [
      { src: '/assets/projects/bayanan-surveying.jpg', caption: 'Director Nico Valencia and his engineer survey the school grounds with the School Head to assess the repairs needed.' },
      { src: '/assets/projects/bayanan-teacher.jpg', caption: 'President Reginald Yu listens as a teacher goes through her list of much-needed improvements, while Director Nico Valencia looks on.' },
      { src: '/assets/projects/bayanan-comfort-room.jpg', caption: 'Rotarians inspect the school’s comfort rooms, one of the repairs the Club has committed to.' },
      { src: '/assets/projects/bayanan-school-head.jpg', caption: 'President Reginald Yu and the School Head walk the grounds and discuss the school’s most urgent needs.' },
    ],
    sources: [
      ['/balita/4105/a-long-walk-toward-hope-rotary-club-of-manila-visits-bayanan-elementary-school-i', 'Balita No. 4105: A Long Walk Toward Hope'],
    ],
  },
  {
    slug: 'project-river',
    archive: 'Pasig River',
    card: 'Project R.I.V.E.R.',
    title: 'Project R.I.V.E.R. at Hospicio de San Jose',
    kicker: 'Water, sanitation and hygiene',
    dek: 'Rotary Initiative for Vulnerability Elimination and Resilience: a high-capacity pump system so the Pasig River home for elderly, abandoned and medically fragile residents can keep caring for them through floods.',
    hero: { src: '/assets/projects/river-marker-2025.jpg', w: 640, h: 523, alt: 'Rotarians steady a ladder as a member mounts the Club’s Four-Way Test marker at Hospicio de San Jose, 9 December 2025' },
    facts: [
      ['Where', 'Hospicio de San Jose, on the Pasig River, Manila'],
      ['Budget', 'P1 million allocated for the pump system'],
      ['Area of focus', 'Water, sanitation and hygiene'],
    ],
    need: [
      'Hospicio de San Jose sits on the Pasig River, so seasonal overflows and heavy rain routinely compromise its sanitation facilities, disrupt daily care, and expose its residents, many of them elderly, abandoned or medically fragile, to serious health and safety risks.',
    ],
    did: [
      ['RY 2025–26', 'Flagship project', 'The Club launched Project R.I.V.E.R. as a flagship project and allocated P1 million to buy and install a high-capacity water pump system.'],
      ['9 December 2025', 'Hospicio de San Jose', 'The Club turned over the project check to Hospicio de San Jose and installed its sixth Four-Way Test marker there.'],
    ],
    result: [
      ['P1M', 'for a high-capacity water pump system'],
    ],
    resultText: 'The pump system is designed to drain floodwater faster, prevent stagnant water and contamination, and keep essential facilities running during severe weather.',
    quote: 'More than a flood control measure, it is a response to the fundamental determinants of dignity.',
    partners: ['Hospicio de San Jose'],
    next: 'The Club continues to work with the Hospicio on health, nutrition and hygiene programs for its residents.',
    gallery: [],
    sources: [
      [null, 'RY 2025–26 report of IPP Raoul C. Creencia'],
      ['/balita/4056/new-rotary-year-kick-off-activity-at-hospicio-de-san-jose', 'Balita No. 4056: New Rotary Year kick-off at Hospicio de San Jose'],
      ['/balita/4073/project-river-building-resilience-through-safer-water-management', 'Balita No. 4073: Project R.I.V.E.R. turnover'],
    ],
  },
  {
    slug: 'aral-scholarships',
    archive: 'scholarship',
    card: 'A.R.A.L. scholarships',
    title: 'A.R.A.L.: study now, pay later',
    kicker: 'Basic education and livelihood',
    dek: 'Advancing Resources for Accessible Learning funds technical training for young people at DUALTECH Training Center. Graduates repay once they are employed, so the next students can train too.',
    hero: { src: '/assets/home/poa-empower-2026.jpg', w: 1800, h: 1350, alt: 'Rotarians watch Dualtech scholars at work on a precision machine during the Club’s visit in September 2026. Text: Together, we empower. Rotary, People of Action.', poa: true },
    facts: [
      ['Scholars', '15 at DUALTECH Training Center'],
      ['Funding', 'P1 million from the Leon Lambert Fellows Fund'],
      ['Area of focus', 'Basic education and literacy; community economic development'],
    ],
    need: [
      'Capable young people from low-income families often cannot afford the industry-ready technical training that leads to stable jobs.',
    ],
    did: [
      ['4 March 2025', 'Planning with DUALTECH', 'Club and RCManila Foundation officers met DUALTECH’s leadership to set up the scholarship program.'],
      ['RY 2025–26', 'Leon Lambert Fellows Fund', 'The Club allocated P1 million to the education and technical training of 15 scholars.'],
      ['December 2025', 'Memorandum of Agreement', 'The Club signed a Memorandum of Agreement with Dualtech Training Center and launched the A.R.A.L. program.'],
      ['September 2026', 'Dualtech Excellence Center, Canlubang, Laguna', 'President Reginald T. Yu, IPP Raoul Creencia and Project Chair Anton Mauricio visited the workshops, watched scholars at work and discussed how to extend the scholarships to more students.'],
    ],
    result: [
      ['15', 'scholars in technical-vocational training'],
      ['P1M', 'revolving fund: repayments pay for the next scholars'],
    ],
    resultText: 'DUALTECH’s German-inspired dual training model combines classroom instruction with supervised on-the-job training in partner industries, so scholars graduate ready for work.',
    partners: ['DUALTECH Training Center', 'Leon Lambert Fellows', 'RCManila Foundation'],
    next: 'As scholars find work and repay, the fund supports new students.',
    gallery: [
      { src: '/assets/projects/aral-machining-2026.jpg', caption: 'Members of the Rotary Club of Manila watch Dualtech scholars in hands-on precision machining training, September 2026.' },
      { src: '/assets/projects/aral-workshop-2026.jpg', caption: 'President Reginald Yu and the Club delegation tour the Dualtech workshops, where trainees operate machinery and install electrical systems.' },
      { src: '/assets/projects/aral-trainee-explains-2026.jpg', caption: 'A trainee walks the Rotarians through an industrial training rig.' },
      { src: '/assets/projects/aral-demo-2026.jpg', caption: 'A Dualtech trainee explains how a digitally powered elevator system works, applying classroom principles to real-world technology.' },
    ],
    sources: [
      [null, 'RY 2025–26 report of IPP Raoul C. Creencia'],
      ['/balita/4042/rcmfi-dualtech-scholarship-program', 'Balita No. 4042: RCMFI DualTech Scholarship Program'],
      ['/balita/4073/moa-signing-with-dualtech-and-launch-of-aral-program', 'Balita No. 4073: MOA signing with Dualtech and launch of A.R.A.L.'],
      ['/balita/4106/where-skill-becomes-hope', 'Balita No. 4106: Where Skill Becomes Hope'],
    ],
  },
];
